version: '3.8'

services:
  php:
    build: .
    container_name: php_container
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge